### ISSUE TITLE
what to do when forgot passphrase?

### ISSUE THREAD

**Issue by adcwcmw** [NeoxaChain/Neoxa#15]
I just need to create a new wallet. I can't find an option to do that.

**Comment by GauchoBois** [comment]
Similar problem here with Mac. Tried to remove the wallet and re-install it but didn't work. Also tried removing the files I found in the Library folder but something sticks somewhere and can't create a new wallet from scratch when re-installing.

A full uninstall feature is also needed in this wallet at least.

**Comment by Luckyblocks-dev** [comment]
> I just need to create a new wallet. I can't find an option to do that.

First, exit Neoxa, shut it down.

Navigate to `C:\Users\userName\AppData\Roaming\Neoxa` and copy `wallet.dat` to a USB stick and save it in case you later remember the passphrase.

Next, AFTER you have backed up `wallet.dat`, from that DIR, then delete the `wallet.dat` file.

After you've deleted the `wallet.dat` file, re-start Neoxa.

You should be good to go with generating new wallet.

**Comment by Luckyblocks-dev** [comment]
@GauchoBois Not sure about Mac as I don't use them, but I guess would be in location like `/Users/<username>/Library/Application Support/Neoxa/neoxa`

You need to do the same thing. Shutdown Neoxa. Backup wallet data file to USB, delete wallet data file from Mac, re-start Neoxa.

**Comment by Sibghatshaikhh** [comment]
Hello,

I have been mining Neoxa since like 6 months. I have recently lost my laptop and I could not recover the data on my PC. So I bought new PC and I reconnected my Neoxa core wallet through my passphrase and mnemonic, after I can not find my balance in my wallet so I opened debug window from tools section and added my receiving address in which I have been mining. After that I can see my balance but it's not spendable its only watch only mode. Can anyone hear help please?


<img width="922" alt="Screenshot 2023-01-18 at 8 04 07 PM" src="https://user-images.githubusercontent.com/122995753/213207731-a4898590-4b72-45d4-bc21-11cb64f25cfa.png">
